# -*- coding: utf-8 -*-
"""2. MANIPULACIÓN DE DATOS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1y8zyhXwMIHfK9_-vuXefyxvKZ60Hhh8k
"""

# Importar las bibliotecas necesarias
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Leer el archivo de Excel y mostrar las primeras filas
df = pd.read_excel('/content/Datos Maestros VF.xlsx')
df.head()

# Definir las columnas a eliminar
columnas_elim = ['Precio de Arranque (Par)', 'Mínimo técnico por central',
                 'Inflexibilidad por unidad para generar AGC (QA-)', 'Minimo Operativo por central (MO del Ofei)',
                 'CENTRAL (OFEI)', 'UNIDAD (OFEI)', 'Nombre visible Central']

# Eliminar las columnas no deseadas y mostrar las primeras filas del DataFrame resultante
df_pros = df.drop(columns=columnas_elim)
df_pros = df_pros.drop('Minimo ténico  por unidad', axis=1)
df_pros.head()

# Ruta del archivo CSV a leer
ruta_archivo = '/content/dDEC1204.TXT'

# Leer el archivo CSV, realizar operaciones y limpiar datos
df_dec_central = pd.read_csv(ruta_archivo, encoding='latin-1', delimiter=',', quotechar='"', header=None)
df_dec_central['Total'] = df_dec_central.iloc[:, 2:].sum(axis=1)
df_dec_central = df_dec_central[df_dec_central['Total'] > 0]
df_dec_central = df_dec_central.drop(columns=df_dec_central.columns[1:25])

# Renombrar las columnas del DataFrame "df_dec_central"
column_nom = {0: 'CENTRAL (dDEC, dSEGDES, dPRU…)', 'Total': 'Total de horas'}
df_dec_central = df_dec_central.rename(columns=column_nom)

# Mostrar las últimas filas del DataFrame "df_dec_central"
df_dec_central.head()
print('=' * 64)
df_dec_central.tail(5)

# Realizar la fusión (merge) de los DataFrames "df_pros" y "df_dec_central"
df_merge = pd.merge(df_pros, df_dec_central, on='CENTRAL (dDEC, dSEGDES, dPRU…)')
df_merge.head()

# Verificar si hay valores de 0 en la columna 'Total de horas'
if (df_merge['Total de horas'] == 0).any():
    print("El DataFrame contiene al menos un valor 0")
else:
    print("El DataFrame no contiene valores 0")

# Crear un nuevo DataFrame "df" y guardar en archivos CSV y Excel
df = pd.DataFrame(df_merge)
df.to_csv('Prueba2.csv', index=False)
df.to_excel('Prueba-2.xlsx', index=False)

# Verificar el tipo de objeto del DataFrame "df"
type(df)